# -*- coding: utf-8 -*-
"""DataVisualization02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_C_jeNzDiMY05VgecHwl9dIgU3rfzRw
"""

#Datavisualization byPython
#Using SEER-BreastCancer.csv for prediction and analysis


import pandas as pd

dataset = pd.read_csv(/kai/liao/BIO/breast-cancer/Breast_Cancer.csv")

dataset.info()
dataset.describe() 
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,4))  
ax1 = ax[0]    # axisx
ax2 = ax[1]    # aixsy

sns.countplot(data=dataset, hue='Status', ax=ax1, x='Race',    ) 
#define x as race
sns.countplot(data=dataset, hue='Status', ax=ax2, x='Marital Status',)
#define x as marital status

plt.tight_layout() 


fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,4))  
ax1 = ax[0]    
ax2 = ax[1]   

sns.countplot(data=dataset, hue='Status', ax=ax1, x='Estrogen Status',    )
#define x as estrogen status
sns.countplot(data=dataset, hue='Status', ax=ax2, x='Progesterone Status',)
#define x as progesterone status

plt.tight_layout() #layout the most suitable format graph

