# -*- coding: utf-8 -*-
"""DataVisualization04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_C_jeNzDiMY05VgecHwl9dIgU3rfzRw
"""

#Datavisualization byPython
#Using SEER-BreastCancer.csv for prediction and analysis


import pandas as pd

dataset = pd.read_csv(/kai/liao/BIO/breast-cancer/Breast_Cancer.csv")

dataset.info()
dataset.describe() 
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,4))  
ax1 = ax[0]    # axisx
ax2 = ax[1]    # aixsy

sns.countplot(data=dataset, hue='Status', ax=ax1, x='Race',    ) 
#define x as race
sns.countplot(data=dataset, hue='Status', ax=ax2, x='Marital Status',)
#define x as marital status

plt.tight_layout() 


fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,4))  
ax1 = ax[0]    
ax2 = ax[1]   

sns.countplot(data=dataset, hue='Status', ax=ax1, x='Estrogen Status',    )
#define x as estrogen status
sns.countplot(data=dataset, hue='Status', ax=ax2, x='Progesterone Status',)
#define x as progesterone status

plt.tight_layout() #layout the most suitable format graph 

fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(14,8))
ax1 = axes[0,0]
ax2 = axes[0,1]
ax3 = axes[0,2]
ax4 = axes[1,0]
ax5 = axes[1,1]
ax6 = axes[1,2]

sns.countplot(data=dataset, hue='Status', ax=ax1, x='T Stage ',     )
sns.countplot(data=dataset, hue='Status', ax=ax2, x='N Stage',      )
sns.countplot(data=dataset, hue='Status', ax=ax3, x='6th Stage',    )
sns.countplot(data=dataset, hue='Status', ax=ax4, x='A Stage',      )
sns.countplot(data=dataset, hue='Status', ax=ax5, x='differentiate',)
sns.countplot(data=dataset, hue='Status', ax=ax6, x='Grade',        )

plt.setp(ax5.get_xticklabels(), rotation=30, ha="right") #visualize the graph ofdifferent settings of Xaxis
plt.tight_layout() 


# straight plot graph survival/death
fig, ax = plt.subplots(figsize=(6,4))

sns.histplot(data=dataset, bins=20, kde=True, ax=ax, hue='Status', x='Age')

