# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kV55CmjB6PHiakpNGvGkj8KOrx8G7rt7
"""

from sklearn.metrics import roc_curve, auc
import numpy
import sklearn
import matplotlib 
import pandas as pd
#Using SEER-BreastCancer.csv for prediction and analysis
#LMFAO team

import statsmodels.api as sm
import statsmodels.formula.api as smf

X = data.iloc[:, :-1]
X['intercept'] = 1.0 
X.head()
x_train, y_train = X.iloc[:3001, :], data.iloc[:3001, -1]
x_test,  y_test  = X.iloc[3001:, :], data.iloc[3001:, -1]

model = sm.Logit(y_train, x_train[cols]).fit()
model.summary()   


dataset = pd.read_csv(/kai/liao/BIO/breast-cancer/Breast_Cancer.csv")

dataset.info()
dataset.describe() 

resu = model.predict(x_test[cols])
fpr, tpr, threshold = roc_curve(y_test, resu)

rocauc = auc(fpr, tpr)
plt.plot(fpr, tpr, 'r', label='AUC = %0.2f' % rocauc)
plt.plot([0, 1], [0, 1], color='grey',linestyle='--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True rate')
plt.xlabel('False rate')
plt.legend(loc='lower right')
plt.show()